pipeline:
  name: ECR
  identifier: ECR
  projectIdentifier: Harness1
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: ECR
        identifier: ECR
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: CreateStack
                  name: CreateStack_1
                  identifier: CreateStack_1
                  spec:
                    provisionerIdentifier: ECR1
                    configuration:
                      stackName: Ecr-stack
                      connectorRef: AWS1
                      region: us-east-1
                      templateFile:
                        type: Remote
                        spec:
                          store:
                            type: Github
                            spec:
                              paths:
                                - ecr1.yaml
                              connectorRef: Github2
                              gitFetchType: Branch
                              branch: master
                      roleArn: ""
                      parameterOverrides:
                        - name: ECRRepo
                          value: repo23789
                          type: String
                  timeout: 10m
        tags: {}
    - stage:
        name: ECS
        identifier: ECS
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: CreateStack
                  name: CreateStack_1
                  identifier: CreateStack_1
                  spec:
                    provisionerIdentifier: ECS23
                    configuration:
                      stackName: Stack-ECS
                      connectorRef: AWS1
                      region: us-east-1
                      templateFile:
                        type: Remote
                        spec:
                          store:
                            type: Github
                            spec:
                              paths:
                                - ecs-merge.yaml
                              connectorRef: Github2
                              gitFetchType: Branch
                              branch: master
                      roleArn: ""
                      parameterOverrides:
                        - name: MinContainers
                          value: <+input>
                          type: String
                        - name: Subnet2
                          value: <+input>
                          type: String
                        - name: ContainerMemory
                          value: <+input>
                          type: String
                        - name: ServiceName
                          value: <+input>
                          type: String
                        - name: ContainerCpu
                          value: <+input>
                          type: String
                        - name: ECSClusterName
                          value: <+input>
                          type: String
                        - name: VPC
                          value: <+input>
                          type: String
                        - name: ContainerPort
                          value: <+input>
                          type: String
                        - name: ImageURI
                          value: <+input>
                          type: String
                        - name: Subnet1
                          value: <+env.variables.Subnet1>
                          type: String
                  timeout: 20m
        tags: {}
