pipeline:
  name: ECS-creation
  identifier: ECScreation
  projectIdentifier: Harness1
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: ecr
        identifier: ecr
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: CreateStack
                  name: CreateStack_1
                  identifier: CreateStack_1
                  spec:
                    provisionerIdentifier: ecr1
                    configuration:
                      stackName: ecr-89
                      connectorRef: AWSACG
                      region: us-east-1
                      templateFile:
                        type: Remote
                        spec:
                          store:
                            type: Github
                            spec:
                              paths:
                                - ecr.yaml
                              connectorRef: Github2
                              gitFetchType: Branch
                              branch: master
                      roleArn: ""
                      parameterOverrides:
                        - name: RepoName
                          value: my-repo12
                          type: String
                  timeout: 10m
        tags: {}
    - stage:
        name: ecs
        identifier: ecs
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: CreateStack
                  name: CreateStack_1
                  identifier: CreateStack_1
                  spec:
                    provisionerIdentifier: ecs
                    configuration:
                      stackName: ecs-cre
                      connectorRef: AWSACG
                      region: us-east-1
                      templateFile:
                        type: Remote
                        spec:
                          store:
                            type: Github
                            spec:
                              paths:
                                - ecs-merge.yaml
                              connectorRef: Github2
                              gitFetchType: Branch
                              branch: master
                      roleArn: ""
                      parameterOverrides:
                        - name: MinContainers
                          value: <+input>
                          type: String
                        - name: ContainerMemory
                          value: <+input>
                          type: String
                        - name: ServiceName
                          value: <+input>
                          type: String
                        - name: ContainerCpu
                          value: <+input>
                          type: String
                        - name: ContainerPort
                          value: <+input>
                          type: String
                        - name: EcsClustername
                          value: <+input>
                          type: String
                        - name: ImageURI
                          value: <+input>
                          type: String
                  timeout: 10m
        tags: {}
