pipeline:
  name: ECS-deploy
  identifier: ECSdeploy
  projectIdentifier: Harness1
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: ECS-dep
        identifier: ECSdep
        description: ""
        type: Deployment
        spec:
          deploymentType: ECS
          service:
            serviceRef: clustercre
          environment:
            environmentRef: ecsenv
            deployToAll: false
            infrastructureDefinitions:
              - identifier: ecseast1
          execution:
            steps:
              - step:
                  type: CreateStack
                  name: CreateStack_1
                  identifier: CreateStack_1
                  spec:
                    provisionerIdentifier: ECS
                    configuration:
                      stackName: ECS-dep
                      connectorRef: AWS1
                      region: us-east-1
                      templateFile:
                        type: Remote
                        spec:
                          store:
                            type: Github
                            spec:
                              paths:
                                - ecs-merge.yaml
                              connectorRef: Github2
                              gitFetchType: Branch
                              branch: master
                      roleArn: ""
                  timeout: 10m
            rollbackSteps: []
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
