pipeline:
  name: ECS-Infra
  identifier: ECSInfra
  projectIdentifier: Harness1
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: ECS
        identifier: ECS
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: CreateStack
                  name: CreateStack_1
                  identifier: CreateStack_1
                  spec:
                    provisionerIdentifier: ECS2
                    configuration:
                      stackName: ECS-infra
                      connectorRef: AWS1
                      region: us-east-1
                      templateFile:
                        type: Remote
                        spec:
                          store:
                            type: Github
                            spec:
                              paths:
                                - ecs-merge.yaml
                              connectorRef: Github2
                              gitFetchType: Branch
                              branch: master
                      roleArn: ""
                  timeout: 10m
        tags: {}
