pipeline:
  name: ecs-image-deploy
  identifier: ecsimagedeploy
  projectIdentifier: Harness1
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: ECR
        identifier: ECR
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: CreateStack
                  name: CreateStack_1
                  identifier: CreateStack_1
                  spec:
                    provisionerIdentifier: ECR
                    configuration:
                      stackName: ecr-creation
                      region: us-east-1
                      templateFile:
                        type: Remote
                        spec:
                          store:
                            type: Github
                            spec:
                              paths:
                                - ecr.yaml
                              connectorRef: Github2
                              gitFetchType: Branch
                              branch: master
                      roleArn: ""
                      connectorRef: AWSACG2
                      parameterOverrides:
                        - name: RepoName1
                          value: ecr-repos
                          type: String
                  timeout: 10m
        tags: {}
    - stage:
        name: ECS
        identifier: ECS
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: CreateStack
                  name: CreateStack_1
                  identifier: CreateStack_1
                  spec:
                    provisionerIdentifier: ECS
                    configuration:
                      stackName: ECs-creation
                      connectorRef: AWSACG2
                      region: us-east-1
                      templateFile:
                        type: Remote
                        spec:
                          store:
                            type: Github
                            spec:
                              paths:
                                - ecs-merge.yaml
                              connectorRef: Github2
                              gitFetchType: Branch
                              branch: master
                      roleArn: ""
                      parameterOverrides:
                        - name: Subnet1
                          value: <+input>
                          type: String
                        - name: MinContainers
                          value: "1"
                          type: String
                        - name: Subnet2
                          value: <+input>
                          type: String
                        - name: ContainerMemory
                          value: 1GB
                          type: String
                        - name: ServiceName
                          value: ser-task
                          type: String
                        - name: ContainerCpu
                          value: "256"
                          type: String
                        - name: VPC
                          value: <+input>
                          type: String
                        - name: ContainerPort
                          value: "80"
                          type: String
                        - name: ImageURI
                          value: <+input>
                          type: String
                        - name: ECSClusterName
                          value: clust-23
                          type: String
                  timeout: 10m
        tags: {}
