pipeline:
  name: Pipeline-K
  identifier: PipelineK
  projectIdentifier: Harness1
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Stage-K
        identifier: StageK
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: CreateStack
                  name: CreateStack_1
                  identifier: CreateStack_1
                  spec:
                    provisionerIdentifier: SkS
                    configuration:
                      stackName: stack99
                      connectorRef: AWS1
                      region: us-east-1
                      templateFile:
                        type: Remote
                        spec:
                          store:
                            type: Github
                            spec:
                              paths:
                                - harness example.yml
                              connectorRef: Conector2
                              gitFetchType: Branch
                              branch: master
                      roleArn: ""
                  timeout: 10m
        tags: {}
  variables:
    - name: s3bucket
      type: String
      description: ""
      required: false
      value: <+input>
    - name: s3bucket1
      type: String
      description: ""
      required: false
      value: <+input>
