pipeline:
  name: Pipeline-K
  identifier: PipelineK
  projectIdentifier: Harness1
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Stage-K
        identifier: StageK
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: CreateStack
                  name: CreateStack_1
                  identifier: CreateStack_1
                  spec:
                    provisionerIdentifier: SkS
                    configuration:
                      stackName: stack99
                      connectorRef: AWS1
                      region: us-east-1
                      templateFile:
                        type: Remote
                        spec:
                          store:
                            type: Github
                            spec:
                              paths:
                                - lab1.1.1.yaml
                              connectorRef: Conector2
                              gitFetchType: Branch
                              branch: master
                      roleArn: ""
                  timeout: 10m
        tags: {}
    - stage:
        name: stage-2
        identifier: stage2
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: S3Upload
                  name: S3Upload_1
                  identifier: S3Upload_1
                  spec:
                    connectorRef: AWS1
                    region: us-east-1
                    bucket: bucket99511
                    sourcePath: https://s3.console.aws.amazon.com/s3/buckets/bucket99511
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Docker
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: Conector2
        build: <+input>
