AWSTemplateFormatVersion: "2010-09-09"
Description: "Ecr repository"
Parameters:
  ECRRepo1: 
    Type: String
Resources:
  Repository1: 
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: !Ref ECRRepo1 
Outputs:
  RepoName:
    Value: !Ref ECRRepo1
 
  
 


