AWSTemplateFormatVersion: "2010-09-09"
Description: "Ecr repository"
Parameters:
  ECRRepo: 
    Type: String
    Description: providing the repo name
Resources:
  Repo1: 
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: !Ref ECRRepo
      Tags:
        - Key: Application
          Value: Ecr1
Outputs:
  RepoName:
    Value: !Ref ECRRepo


  
 


