AWSTemplateFormatVersion: "2010-09-09"
Description: "s3 bucket creation"
Parameters:
  Bucket12:
    Type: String
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref Bucket12
