Parameters:AWSTemplateFormatVersion: "2010-09-09"
Description: "Managedpolicy to user"
Resources:
  IamUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref UserName
      LoginProfile:
        Password: !Ref UserPassword
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess