AWSTemplateFormatVersion: "2010-09-09"
Description: "s3 bucket creation"
Parameters:
  BucketName:
    Type: String
    Description: name of the s3 bucket
Resources:
  s3:
    Properties: !Ref BucketName
      
