AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda behind API Gateway
Parameters:
  FunName: 
    Type: String
Resources: 
  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref FunName
      Runtime: python3.9
      Role: !GetAtt LambdaRole.Arn
      Handler: index.my_handler
      Code:
        ZipFile: |
          import json

          def my_handler(event,context):
              return {
                  'statusCode': 200,
                  'body': json.dumps('Hello from Lambda!')
              }
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambda_FullAccess
            
