AWSTemplateFormatVersion: "2010-09-09"
Description: "Creation of secrets"
Parameters:
  AppCI:
    Type: String
    Default: agr
  SecretName:
    Type: String
  ReplicaRegion:
    Type: String
    Default: us-east-2
  SecretStringdev:
   Type: String
Resources:
  AgrSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Ref SecretName
      Description: "This secret will use to connect"
      SecretString: !Sub '{"username":"MasterUsername","password":"secret-password"}'
      ReplicaRegions:
        - Region: !Ref ReplicaRegion
      Tags:
        -
          Key: ApplicationCI
          Value: !Ref AppCI