Parameters:
  Servicename:
    Type: String
  VPC:
    Type: String
  Subnet1:
    Type: String
  Subnet2:
    Type: String
Resources:
  MyECSService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Ref Servicename
      Cluster: ecs-clu
      TaskDefinition: 
        Fn::ImportValue: ImportValue1
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref Subnet1
            - !Ref Subnet2
        
